integrationName: aerospike
humanReadableIntegrationName: Aerospike
definitions:
  - type: AEROSPIKE_INSTANCE
    conditions:
      - attribute: metricName
        prefix: aerospike_
  - type: NOT_MATCHING
    conditions:
      - attribute: metricName
        prefix: neverMatching
